CREATE TABLE `trace_data` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水id',
	`role_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '玩家id',
	`open_id` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '平台Id',
	`server` VARCHAR(10) NOT NULL DEFAULT '0' COMMENT '服务器id',
	`trace_data` VARCHAR(2000) NOT NULL DEFAULT '0' COMMENT 'trace数据',
	`user_ip` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '玩家ip地址',
	`user_agent` VARCHAR(1000) NOT NULL DEFAULT '0' COMMENT 'User-Agent',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
	PRIMARY KEY (`id`)
)
COMMENT='trace data store'
ENGINE=InnoDB;